### ISSUE TITLE
 Get.dismiss(); 不起作用呢

### ISSUE THREAD

**Issue by demidroid** [yuexunshi/todo#2]
extension GetExtension on GetInterface {
  dismiss() {
    if (Get.isDialogOpen) {
      Get.back();
    }
  }

  loading() {
    if (Get.isDialogOpen) {
      Get.back();
    }
    Get.dialog(LoadingDialog());
  }
}
dismiss ,请问，问啥弹框不隐藏呢

**Comment by yuexunshi** [comment]
弹出的是dialog类型的吗

**Comment by demidroid** [comment]
> 
> 
> 弹出的是dialog类型的吗

代码写错了，可以了，谢谢
